export const ROUTES = {
  CAMERA: "/pages/camera/camera",
  SHOP: "/pages/shop/shop",
  LOGIN: "/pages/login/login",
  PERSONAL: "/pages/personal/personal",
  DETAIL: "/pages/detail/detail",
  CUSTOMER: "/pages/customer/customer",
  INDEX: "/pages/index/index",
  WEBVIEW: "/pages/webview/webview",
};

export const GENDER = {
  0: "男",
  1: "女",
};

export const STATUSCODES = [429, 500];

export const LOGIN_TYPE = {
  WEIXIN: "weixin",
  QQ: "qq",
  PHONE: "phone",
  APPLE: "apple",
  SINA: "sina",
  GOOGLE: "google",
  FACEBOOK: "facebook",
};

export const ERROR_CODES = {
  0: "登录失败",
  "-1": "参数错误",
  "-2": "用户取消",
  "-3": "此功能不支持",
  "-4": "文件不存在",
  "-5": "IO错误",
  "-6": "网络错误",
  "-7": "业务参数配置缺失",
  "-8": "客户端未安装",
  "-9": "快捷方式已存在",
  "-10": "授权失败",
  "-99": "未知错误",
  "-100": "业务内部错误",
  "-1001": "未登录或登录已注销",
  "-1002": "获取Token失败",
  "-1201": "WGT/WGTU文件格式错误",
  "-1202": "WGT安装包中manifest.json文件不存在",
  "-1203": "WGT安装包中manifest.json文件格式错误",
  "-1204": "WGT安装包中manifest.json文件的appid不匹配",
  "-1205": "WGT安装包中manifest.json文件的version版本不匹配",
  "-1221": "WGTU安装包中update.xml文件不存在",
  "-1222": "WGTU安装包中update.xml文件格式错误",
  "-1223": "WGTU安装包中update.xml文件的appid不匹配",
  "-1224": "WGTU安装包中update.xml文件的version版本不匹配",
  "-1225": "WGTU安装包中www目录下manifest.json不存在",
  "-1226": "WGTU安装包中www目录下manifest.json文件格式错误",
  "-1227": "WGTU安装包中www目录下manifest.json文件的appid不匹配",
  "-1228": "WGTU安装包中www目录下manifest.json文件的version版本不匹配",
  "-1229": "HTML5+ Runtime缺少升级包manifest.json中配置的模块",
  "-1250": "uni-app编译模式切换不支持升级应用资源",
  "-1301": "文件播放格式错误",
  "-1302": "文件请求超时",
  "-1401": "数据库没有打开",
  "-1402": "数据库已经打开",
  "-1403": "WWW目录下的数据库只有读权限",
  "-1404": "其他错误",
  "-1501": "坐标地址解析失败",
  "-1502": "坐标地址获取失败",
  "-1503": "不支持某个提供者，如：不支持腾讯地图",
  "-1504": "坐标系类型不支持",
  "-1505": "定位服务不能用",
  1000: "当前 uniAppid 尚未开通一键登录",
  1001: "应用所有者账号信息异常，请检查账号一键登录服务是否正常",
  1002: "应用所有者账号信息异常，请检查账号余额是否充足",
  4001: "请求参数异常",
  4003: "开发者账户appid 校验异常，联系官方人员",
  5000: "服务器未知异常，联系官方人员",
  30001: "当前网络环境不适合执行该操作",
  30002: "用户点击了其他登录方式",
  30003: "用户关闭验证界面",
  30004: "其他错误",
  30005: "预登录失败",
  30006: "一键登录失败",
  30007: "获取本机号码校验token失败",
  40004: "应用不存在",
  40047: "一键登录取号失败",
  40053: "手机号校验失败",
  40201: "源IP鉴权失败",
};
